trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Frontend/** 

pool:
  vmImage: ubuntu-latest

variables:
  app_location: '/Frontend'
  output_location: 'dist'
  api_location: ''     

steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'SeaOakARMServiceConnection' 
      KeyVaultName: 'oak-chatgpt-keyvault'  
      SecretsFilter: 'SeaOakWebUiDeploymentKey'
      RunAsPreJob: false
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js'

  - script: |
      cd Frontend
      npm install
      npm run build
    displayName: 'Install dependencies and build Vue.js app'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: $(app_location)
      output_location: $(output_location)
      api_location: $(api_location)
      azure_static_web_apps_api_token: $(SeaOakWebUiDeploymentKey) # Get value from KeyVault @AzureKeyVault@2
    displayName: 'Deploy to Azure Static Web Apps'
